[database]
path = "call_qa_production.db"

[convoso]
api_token = "1d7lf53gyeqjf1ulpsy26tad86ppkzfb"
base_url = "https://api.convoso.com/v1"
timeout = 30
integration_enabled = true

[api_keys]
openai = "sk-your-openai-api-key-here"

[lead_vendors]
google_ads = "your-google-ads-api-key"
facebook_ads = "your-facebook-ads-api-key"
bing_ads = "your-bing-ads-api-key"

[ftp]
username = "callqa_user"
password = "secure_password_2025"
host = "localhost"
port = 21

[processing]
whisper_model = "large"
max_threads = 8
retention_hours = 24
data_retention_days = 365
